/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    media: Media;
    customers: Customer;
    invoices: Invoice;
    quotes: Quote;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'shop-info': ShopInfo;
  };
  globalsSelect: {
    'shop-info': ShopInfoSelect<false> | ShopInfoSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  price: number;
  sku?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  companyName: string;
  email?: string | null;
  vatNumber?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: string;
  issueDate?: string | null;
  dueDate?: string | null;
  client: {
    /**
     * Select a customer to auto-fill client details
     */
    customer?: (string | null) | Customer;
    name: string;
    email?: string | null;
    address?: {
      street?: string | null;
      city?: string | null;
      postalCode?: string | null;
      country?: string | null;
    };
    vatNumber?: string | null;
  };
  items?:
    | {
        /**
         * Select a product to auto-fill description and price
         */
        product?: (string | null) | Product;
        /**
         * Auto-filled when a product is selected. Changing the product overrides this value.
         */
        description: string;
        quantity: number;
        /**
         * Auto-filled when a product is selected. Changing the product overrides this value.
         */
        unitPrice: number;
        taxRate?: number | null;
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  subtotal?: number | null;
  taxTotal?: number | null;
  total?: number | null;
  generatedPdfs?: (string | Media)[] | null;
  invoiceNumber?: string | null;
  status?: ('draft' | 'sent' | 'paid' | 'overdue' | 'cancelled') | null;
  template?: ('Classic' | 'Modern' | 'Minimal' | 'Bold' | 'Corporate') | null;
  lastSentAt?: string | null;
  sendHistory?:
    | {
        sentAt?: string | null;
        to?: string | null;
        templateUsed?: string | null;
        subject?: string | null;
        attachedPdf?: (string | null) | Media;
        sentBy?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  sourceQuote?: (string | null) | Quote;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: string;
  issueDate?: string | null;
  validUntil?: string | null;
  client: {
    /**
     * Select a customer to auto-fill client details
     */
    customer?: (string | null) | Customer;
    name: string;
    email?: string | null;
    address?: {
      street?: string | null;
      city?: string | null;
      postalCode?: string | null;
      country?: string | null;
    };
    vatNumber?: string | null;
  };
  items?:
    | {
        /**
         * Select a product to auto-fill description and price
         */
        product?: (string | null) | Product;
        /**
         * Auto-filled when a product is selected. Changing the product overrides this value.
         */
        description: string;
        quantity: number;
        /**
         * Auto-filled when a product is selected. Changing the product overrides this value.
         */
        unitPrice: number;
        taxRate?: number | null;
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  subtotal?: number | null;
  taxTotal?: number | null;
  total?: number | null;
  acceptToken?: string | null;
  rejectToken?: string | null;
  tokenExpiresAt?: string | null;
  rejectionReason?: string | null;
  generatedPdfs?: (string | Media)[] | null;
  quoteNumber?: string | null;
  status?: ('draft' | 'sent' | 'accepted' | 'rejected' | 'expired') | null;
  template?: ('Classic' | 'Modern' | 'Minimal' | 'Bold' | 'Corporate') | null;
  lastSentAt?: string | null;
  sendHistory?:
    | {
        sentAt?: string | null;
        to?: string | null;
        templateUsed?: string | null;
        subject?: string | null;
        attachedPdf?: (string | null) | Media;
        sentBy?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  relatedInvoices?: (string | Invoice)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'invoices';
        value: string | Invoice;
      } | null)
    | ({
        relationTo: 'quotes';
        value: string | Quote;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  sku?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  companyName?: T;
  email?: T;
  vatNumber?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  issueDate?: T;
  dueDate?: T;
  client?:
    | T
    | {
        customer?: T;
        name?: T;
        email?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              postalCode?: T;
              country?: T;
            };
        vatNumber?: T;
      };
  items?:
    | T
    | {
        product?: T;
        description?: T;
        quantity?: T;
        unitPrice?: T;
        taxRate?: T;
        lineTotal?: T;
        id?: T;
      };
  notes?: T;
  subtotal?: T;
  taxTotal?: T;
  total?: T;
  generatedPdfs?: T;
  invoiceNumber?: T;
  status?: T;
  template?: T;
  lastSentAt?: T;
  sendHistory?:
    | T
    | {
        sentAt?: T;
        to?: T;
        templateUsed?: T;
        subject?: T;
        attachedPdf?: T;
        sentBy?: T;
        id?: T;
      };
  sourceQuote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  issueDate?: T;
  validUntil?: T;
  client?:
    | T
    | {
        customer?: T;
        name?: T;
        email?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              postalCode?: T;
              country?: T;
            };
        vatNumber?: T;
      };
  items?:
    | T
    | {
        product?: T;
        description?: T;
        quantity?: T;
        unitPrice?: T;
        taxRate?: T;
        lineTotal?: T;
        id?: T;
      };
  notes?: T;
  subtotal?: T;
  taxTotal?: T;
  total?: T;
  acceptToken?: T;
  rejectToken?: T;
  tokenExpiresAt?: T;
  rejectionReason?: T;
  generatedPdfs?: T;
  quoteNumber?: T;
  status?: T;
  template?: T;
  lastSentAt?: T;
  sendHistory?:
    | T
    | {
        sentAt?: T;
        to?: T;
        templateUsed?: T;
        subject?: T;
        attachedPdf?: T;
        sentBy?: T;
        id?: T;
      };
  relatedInvoices?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-info".
 */
export interface ShopInfo {
  id: string;
  companyName: string;
  companyLogo?: (string | null) | Media;
  address?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  vatNumber?: string | null;
  siret?: string | null;
  iban?: string | null;
  bic?: string | null;
  bankName?: string | null;
  legalMentions?: string | null;
  defaultPaymentTerms?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-info_select".
 */
export interface ShopInfoSelect<T extends boolean = true> {
  companyName?: T;
  companyLogo?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  phone?: T;
  email?: T;
  website?: T;
  vatNumber?: T;
  siret?: T;
  iban?: T;
  bic?: T;
  bankName?: T;
  legalMentions?: T;
  defaultPaymentTerms?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}